FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Turbopack doesn't play super well with docker in dev mode sometimes without host binding,
# but we will just run npm run dev
CMD ["npm", "run", "dev"]
