from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Iterable, Any

from recongraph.graph.review import ReviewPacket, ReviewOutcome

@dataclass(frozen=True)
class LearnedInsight(ABC):
    """Base class for structured insights generated by LearningAgents."""
    agent_id: str
    metadata: dict[str, Any]

class LearningAgent(ABC):
    """
    Protocol for AI/ML agents that observe human review outcomes
    and generate structured insights.
    """
    
    @abstractmethod
    def get_name(self) -> str:
        """Returns the identifier of this learning agent."""
        pass
        
    @abstractmethod
    def observe(self, packet: ReviewPacket, outcome: ReviewOutcome) -> None:
        """Consumes a human decision and updates internal state."""
        pass
        
    @abstractmethod
    def get_insights(self) -> Iterable[LearnedInsight]:
        """Emits any generated insights for the engine to ingest."""
        pass
